0908/Gwanju01/Gwanju01/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/',include('accounts.urls'))
]

0908/Gwanju01/accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup,name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

0908/Gwanju01/articles/urls.py
from django.urls import path
from . import views

app_name='articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

0908/Gwanju01/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    class Meta(AbstractUser.Meta):
        swappable = 'AUTH_USER_MODEL'

0908/Gwanju01/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title=models.CharField(max_length=20)
    content=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

0908/Gwanju01/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CustomerCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

class CustomerUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields=('email','first_name','last_name',)

0908/Gwanju01/articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'maxlength' : 10,
                'placeholder' : 'title',
            }
        )
    )
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'placeholder':'content',
                'rows':5,
                'columns':50,
            }
        )
    )
    class Meta:
        model=Article
        fields='__all__'

0908/Gwanju01/accounts/views.py
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.shortcuts import render,redirect
from django.contrib.auth import login as auth_login,logout as auth_logout,update_session_auth_hash
from .forms import CustomerCreationForm, CustomerUserChangeForm

# Create your views here.
@require_http_methods(['GET','POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method=='POST':
        form=AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
        pass
    else:
        form=AuthenticationForm()
    context={
        'form':form
    }
    return render(request,'accounts/login.html',context)

@require_POST
def logout(request):
    auth_logout(request)
    return redirect('articles:index')

@require_http_methods(['GET','POST'])
def signup(request):
    if request.method =='POST':
        form = CustomerCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request,user)
            return redirect('articles:index')
    else:
        form = CustomerCreationForm()
    context={
        'form': form,
    }
    return render(request,'accounts/signup.html',context)

@login_required
@require_http_methods(['GET','POST'])
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('articles:index')

@login_required
@require_http_methods(['GET','POST'])
def update(request):
    if request.method == 'POST':
        form = CustomerUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomerUserChangeForm(instance=request.user)
    context={
        'form':form,
    }
    return render(request, 'accounts/update.html', context)

@login_required
@require_http_methods(['GET','POST'])
def change_password(request):
    if request.method=='POST':
        form = PasswordChangeForm(request.user,request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('articles:index')
        pass
    else:
        form= PasswordChangeForm(request.user)
    context={
        'form':form,
    }
    return redirect(request,'accounts/change_paswword.html',context)

0908/Gwanju01/articles/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.decorators.http import require_safe, require_http_methods, require_POST
from .models import Article
from .forms import ArticleForm
# Create your views here.

@require_safe
def index(request):
    articles=Article.objects.all()
    context = {
        'articles' : articles,
    }
    return render(request, 'articles/index.html', context)

@login_required
@require_http_methods(['GET','POST'])
def create(request):
    if request.method=='POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article=form.save()
            return redirect('articles:detail',article.pk)
    else:
        form = ArticleForm()
    context={
        'form':form
        }
    return render(request,'articles/create.html',context)

@require_safe
def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context={
        'article':article,
    }
    return render(request,'articles/detail.html',context)

@login_required
@require_POST
def delete(request, pk):
    if request.user.is_authenticated:
        article = Article.objects.get(pk=pk)
        article.delete()
    return redirect('articles:index')

@login_required
@require_http_methods(['GET', 'POST'])
def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        'article': article,
        'form': form,
    }
    return render(request, 'articles/update.html', context)

0908/Gwanju01/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block content %}
<h1>비밀번호 변경</h1>
<form action="{% url 'accounts:change_password' %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>
{% endblock content %}

0908/Gwanju01/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<h1>로그인</h1>
<form action="" method ="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="login">
</form>
{% endblock content %}

0908/Gwanju01/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'accounts:signup' %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type='submit'>
</form>
{% endblock content %}

0908/Gwanju01/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% block content %}
<h1>회원정보 수정</h1>
<form action="{% url 'accounts:update' %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>
{% endblock content %}

0908/Gwanju01/articles/templates/articles/create.html
{% extends 'base.html' %}
{% block content %}
<h1><b>CREATE</b></h1>
<form action="{% url 'articles:create' %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="SUBMIT">
</form>
<hr>
<a href= "{% url 'articles:index' %}">[back]</a>
{% endblock content %}

0908/Gwanju01/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block content %}
<h1><b>DETAIL</b></h1>
  <hr>
  <p>제목 : {{ article.title }}</p>
  <p>내용 : {{ article.content }}</p>
  <p>작성 시각 : {{ article.created_at }}</p>
  <p>수정 시각 : {{ article.updated_at }}</p>
  <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제">
  </form>
  <hr>
  <a href="{% url 'articles:index' %}">[back]</a>
{% endblock content %}

0908/Gwanju01/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block content %}
<h1><b>INDEX</b></h1>
{% if request.user.is_authenticated %}

<a href="{% url 'articles:create' %}">[CREATE]</a>
{% else %}
<a href="{% url 'accounts:login' %}">새 글을 작성하려면 로그인하세요</a>
{% endif %}
<hr>
{% for article in articles %}
{{article.pk}}
{{article.title}}
<a href= "{% url 'articles:detail' article.pk %}">[detail]</a>
{% endfor %}
{% endblock content %}

0908/Gwanju01/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'articles:detail' article.pk %}">뒤로가기</a>
{% endblock content %}

0908/Gwanju01/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>
  <div class='container'>
    {% if request.user.is_authenticated %}
    <h3>Hello, {{user}}</h3>
    <form action="{% url 'accounts:logout' %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="Logout">
    </form>
    <a href="{% url 'accounts:update' %}">회원정보 수정</a>
    <form action="{% url 'accounts:delete' %}" method="POST">
      {% csrf_token %}
      <input type="submit" value='회원탈퇴'>
    </form>
    {% else %}
    <a href="{% url 'accounts:login' %}">Login</a>
    <a href= "{% url 'accounts:signup' %}">Signup</a>
    {%endif%}
    <hr>
    {% block content %}{% endblock content %}
  </div>
  <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</html>