day6/day6_problem1/memos/urls.py
from django.urls import path
from . import views

app_name = 'memos'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

day6/day6_problem1/project1/project1/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

day6/day6_problem1/project1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('memos/',include('memos.urls')),
]

day6/day6_problem1/memos/models.py
from django.db import models

# Create your models here.
class Memo(models.Model):
    memo = models.TextField()
    summary = models.CharField(max_length=20)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.memo

day6/day6_problem1/memos/forms.py
from django import forms
from .models import Memo

class MemoForm(forms.ModelForm):
    summary = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'summary',
                'maxlength': 20,
            }
        )
    )
    memo = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'placeholder': 'memo',
                'rows': 5,
                'cols': 50,
            }
        )
        )
    class Meta:
        model = Memo
        fields = '__all__'
        # exclude = ('title',)

day6/day6_problem1/memos/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_safe, require_http_methods, require_POST
from .models import Memo
from .forms import MemoForm

# Create your views here.
@require_safe
def index(request):
    # DB에 전체 데이터를 조회
    memos = Memo.objects.all()
    context = {
        'memos': memos,
    }
    return render(request, 'memos/index.html', context)

@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        # create
        form = MemoForm(request.POST)
        if form.is_valid():
            memoi = form.save()
            return redirect('memos:detail', memoi.pk)
    else:
        # new
        form = MemoForm()
    context = {
        'form': form,
    }
    return render(request, 'memos/create.html', context)


@require_safe
def detail(request, pk):
    # variable routing으로 받은 pk 값으로 데이터를 조회
    memo = Memo.objects.get(pk=pk)
    context = {
        'memo': memo,
    }
    return render(request, 'memos/detail.html', context)


@require_POST
def delete(request, pk):
    memo = Memo.objects.get(pk=pk)
    memo.delete()
    return redirect('memos:index')


@require_http_methods(['GET', 'POST'])
def update(request, pk):
    memo = Memo.objects.get(pk=pk)
    if request.method == 'POST':
        form = MemoForm(request.POST, instance=memo)
        # form = MemoForm(data=request.POST, instance=memo)
        if form.is_valid():
            form.save()
            return redirect('memos:detail', memo.pk)
    else:
        form = MemoForm(instance=memo)
    context = {
        'memo': memo,
        'form': form,
    }
    return render(request, 'memos/update.html', context)

day6/day6_problem1/memos/templates/memos/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1><b>CREATE</b></h1>
  <form action="{% url 'memos:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'memos:index' %}">[back]</a>
  <hr>
{% endblock content %}

day6/day6_problem1/memos/templates/memos/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1><b>DETAIL</b></h1>
  <hr>
  <p>요약 : {{ memo.summary }}</p>
  <p>메모 : {{ memo.memo }}</p>
  <p>작성 시각 : {{ memo.created_at }}</p>
  <p>수정 시각 : {{ memo.updated_at }}</p>
  <form action="{% url 'memos:delete' memo.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제">
  </form>
  <hr>
  <a href="{% url 'memos:index' %}">[back]</a>
{% endblock content %}

day6/day6_problem1/memos/templates/memos/index.html
{% extends 'base.html' %}

{% block content %}
  <h1><b>memos</b></h1>
  <a href="{% url 'memos:create' %}">메모하기</a>
  <hr>
  {% for memo in memos %}
  <li>
    <a href="{% url 'memos:detail' memo.pk %}">{{ memo.summary }}</a>
    <p>{{ memo.created_at }}</p>
  </li>
  {% endfor %}
{% endblock content %}

day6/day6_problem1/memos/templates/memos/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <form action="{% url 'memos:update' memo.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    {% comment %} <label for="title">Title: </label>
    <input type="text" name="title" id="title" value="{{ memo.title }}"><br>
    <label for="content">Content: </label>
    <textarea name="content" id="content">{{ memo.content }}</textarea> {% endcomment %}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'memos:detail' memo.pk %}">뒤로가기</a>
{% endblock content %}