day6/day6_problem2/project2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('travels/',include('travels.urls'))
]

day6/day6_problem2/travels/urls.py
from django.urls import path
from . import views

app_name = 'travels'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
]

day6/day6_problem2/travels/models.py
from django.db import models

# Create your models here.
class Travel(models.Model):
    location = models.CharField(max_length=10)
    plan = models.TextField()
    start_date = models.DateField()
    end_date=models.DateField()

    def __str__(self):
        return self.location

day6/day6_problem2/travels/forms.py
from logging import PlaceHolder
from django import forms
from .models import Travel

class TravelForm(forms.ModelForm):
    location = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'ex) 제주도',
                'maxlength': 10,
            }
        )
    )
    plan = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'placeholder': 'ex) 슉.슈슉.',
            }
        )
        )
    start_date = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'placeholder': 'ex) 2022-02-22',
            }
        )
        )
    end_date = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'placeholder': 'ex) 2022-02-22',
            }
        )
        )
    class Meta:
        model = Travel
        fields = '__all__'
        # exclude = ('title',)

day6/day6_problem2/travels/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_safe, require_http_methods, require_POST
from .models import Travel
from .forms import TravelForm

# Create your views here.
@require_safe
def index(request):
    # DB에 전체 데이터를 조회
    travels = Travel.objects.all()
    context = {
        'travels': travels,
    }
    return render(request, 'travels/index.html', context)

@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        # create
        form = TravelForm(request.POST)
        if form.is_valid():
            traveli = form.save()
            return redirect('travels:detail', traveli.pk)
    else:
        # new
        form = TravelForm()
    context = {
        'form': form,
    }
    return render(request, 'travels/create.html', context)


@require_safe
def detail(request, pk):
    # variable routing으로 받은 pk 값으로 데이터를 조회
    travel = Travel.objects.get(pk=pk)
    context = {
        'travel': travel,
    }
    return render(request, 'travels/detail.html', context)


@require_POST
def delete(request, pk):
    travel = Travel.objects.get(pk=pk)
    travel.delete()
    return redirect('travels:index')


@require_http_methods(['GET', 'POST'])
def update(request, pk):
    travel = Travel.objects.get(pk=pk)
    if request.method == 'POST':
        form = TravelForm(request.POST, instance=travel)
        # form = travelForm(data=request.POST, instance=travel)
        if form.is_valid():
            form.save()
            return redirect('travels:detail', travel.pk)
    else:
        form = TravelForm(instance=travel)
    context = {
        'travel': travel,
        'form': form,
    }
    return render(request, 'travels/update.html', context)

day6/day6_problem2/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <aside></aside>
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

day6/day6_problem2/travels/templates/travels/create.html
{% extends 'base.html' %}

{% block content %}
  <h1><b>CREATE</b></h1>
  <form action="{% url 'travels:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'travels:index' %}">[back]</a>
  <hr>
{% endblock content %}

day6/day6_problem2/travels/templates/travels/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1><b>DETAIL</b></h1>
  <p><h1>{{travel.pk}}번째 글</h1><p>
  <hr>
  <p>장소 : {{ travel.location }}</p>
  <p>계획 : {{ travel.plan }}</p>
  <p>시작일 : {{ travel.start_date }}</p>
  <p>종료일 : {{ travel.end_date }}</p>
  <form action="{% url 'travels:delete' travel.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE">
  </form>
  <a href="{% url 'travels:update' travel.pk %}">[UPDATE]</a>
  <hr>
  <a href="{% url 'travels:index' %}">[back]</a>
{% endblock content %}

day6/day6_problem2/travels/templates/travels/index.html
{% extends 'base.html' %}

{% block content %}
  <h1><b>travels</b></h1>
  <a href="{% url 'travels:create' %}">CREATE</a>
  <hr>
  {% for travel in travels %}
  <p>장소 : {{ travel.location }}</p>
  <p>시작일 : {{ travel.start_date }}</p>
    <a href="{% url 'travels:detail' travel.pk %}">[detail]</a>
  <hr>
  {% endfor %}
{% endblock content %}

day6/day6_problem2/travels/templates/travels/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <form action="{% url 'travels:update' travel.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
     <input type="submit">
  </form>
  <hr>
  <a href="{% url 'travels:detail' travel.pk %}">뒤로가기</a>
{% endblock content %}